nome = ()
nome = input('Digite seu nome completo: ')

print(f'Seu nome completo é: {nome}')
print('O seu nome possue {} letras' .format(len(nome) - nome.count(' ')))
print(f'A primeira letra em maiuscula: {nome.capitalize()}')
print(f'Seu nome em MAIUSCULA: {nome.upper()}')
print(f'Seu nome em minusculo: {nome.lower()}')
print(f'Seu nome de forma correta: {nome.title()}')
nome1 = nome.split()
print(f'Seu Primeiro nome é: {nome1[0].capitalize()}')
print(f'Seu primeiro nome tem {len(nome1[0])} letras')
print(f'Seu ultimo nome é:  {nome1[-1].capitalize()}')
meio = int(len(nome1) / 2)
print(f'Seu nome do meio é: {nome1[meio]}')
print('colocando - no seu nome: {}' .format('-'.join(nome1)))